// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolTournamentManager.Data.Persistence;

#nullable disable

namespace PoolTournamentManager.Data.Migrations
{
    [DbContext(typeof(PoolTournamentDbContext))]
    [Migration("20260711134213_AddEntrantWaitlist")]
    partial class AddEntrantWaitlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.BracketDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("BracketDetails");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.BracketNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BracketDetailId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FeedsIntoLoserNodeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeedsIntoLoserSlot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FeedsIntoWinnerNodeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeedsIntoWinnerSlot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGrandFinalReset")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionInRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Slot1EntrantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Slot1IsBye")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Slot2EntrantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Slot2IsBye")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BracketDetailId");

                    b.HasIndex("MatchId");

                    b.ToTable("BracketNodes");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipGameDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChipRatingSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingChips")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("ChipGameDetails");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipGameEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChipGameDetailId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoserEntrantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WinnerEntrantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChipGameDetailId");

                    b.HasIndex("LoserEntrantId");

                    b.HasIndex("TableId");

                    b.HasIndex("WinnerEntrantId");

                    b.ToTable("ChipGameEntries");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipStartingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChipGameDetailId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Chips")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChipGameDetailId");

                    b.ToTable("ChipStartingRules");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BracketNodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Player1EntrantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Player1Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Player2EntrantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Player2Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WinnerEntrantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Player1EntrantId");

                    b.HasIndex("Player2EntrantId");

                    b.HasIndex("TableId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApaEightBallSkill")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApaNineBallSkill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FargoRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TapRating")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.RingGameDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyInAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CurrentShooterEntrantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FiveBallPayout")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NineBallPayout")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("RingGameDetails");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.RingLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntrantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RingGameDetailId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntrantId");

                    b.HasIndex("RingGameDetailId");

                    b.ToTable("RingLedgerEntries");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HostFeePercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedingRatingSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesTeams")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.TournamentEntrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChipAdjustment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWaitlisted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartingChips")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentEntrants");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.TournamentPrizePlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPrizePlaces");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.BracketDetail", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithOne("Bracket")
                        .HasForeignKey("PoolTournamentManager.Core.Entities.BracketDetail", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.BracketNode", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.BracketDetail", null)
                        .WithMany("Nodes")
                        .HasForeignKey("BracketDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTournamentManager.Core.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipGameDetail", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithOne("ChipGame")
                        .HasForeignKey("PoolTournamentManager.Core.Entities.ChipGameDetail", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipGameEntry", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.ChipGameDetail", null)
                        .WithMany("Entries")
                        .HasForeignKey("ChipGameDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolTournamentManager.Core.Entities.TournamentEntrant", "LoserEntrant")
                        .WithMany()
                        .HasForeignKey("LoserEntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTournamentManager.Core.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolTournamentManager.Core.Entities.TournamentEntrant", "WinnerEntrant")
                        .WithMany()
                        .HasForeignKey("WinnerEntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoserEntrant");

                    b.Navigation("Table");

                    b.Navigation("WinnerEntrant");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipStartingRule", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.ChipGameDetail", null)
                        .WithMany("StartingRules")
                        .HasForeignKey("ChipGameDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Match", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.TournamentEntrant", "Player1Entrant")
                        .WithMany()
                        .HasForeignKey("Player1EntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTournamentManager.Core.Entities.TournamentEntrant", "Player2Entrant")
                        .WithMany()
                        .HasForeignKey("Player2EntrantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolTournamentManager.Core.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1Entrant");

                    b.Navigation("Player2Entrant");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.RingGameDetail", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithOne("RingGame")
                        .HasForeignKey("PoolTournamentManager.Core.Entities.RingGameDetail", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.RingLedgerEntry", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.TournamentEntrant", "Entrant")
                        .WithMany()
                        .HasForeignKey("EntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolTournamentManager.Core.Entities.RingGameDetail", null)
                        .WithMany("LedgerEntries")
                        .HasForeignKey("RingGameDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrant");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Table", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithMany("Tables")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.TournamentEntrant", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolTournamentManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithMany("Entrants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.TournamentPrizePlace", b =>
                {
                    b.HasOne("PoolTournamentManager.Core.Entities.Tournament", null)
                        .WithMany("PrizePlaces")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.BracketDetail", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.ChipGameDetail", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("StartingRules");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.RingGameDetail", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("PoolTournamentManager.Core.Entities.Tournament", b =>
                {
                    b.Navigation("Bracket");

                    b.Navigation("ChipGame");

                    b.Navigation("Entrants");

                    b.Navigation("Matches");

                    b.Navigation("PrizePlaces");

                    b.Navigation("RingGame");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
